apiVersion: v2
name: gateway-api-crds
description: A Helm chart to install and manage Kubernetes Gateway API Custom Resource Definitions (CRDs)
type: application
version: 1.5.1
appVersion: 1.5.1
icon: https://raw.githubusercontent.com/peterweissdk/helm/main/img/gatewayapi-logo.png
home: https://gateway-api.sigs.k8s.io/
sources:
  - https://github.com/kubernetes-sigs/gateway-api
  - https://github.com/peterweissdk/helm
keywords:
  - gateway-api
  - crds
  - kubernetes
  - ingress
  - networking
maintainers:
  - name: peterweissdk
    email: peterweissdk@gmail.com
annotations:
  artifacthub.io/license: GPL-3.0
  artifacthub.io/signKey: |
    fingerprint: DE87F96306A52EB766574CB285B6C2B54BCC7FF2
    url: https://peterweissdk.github.io/helm/pubkey.asc
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/peterweissdk/helm/tree/main/charts/gateway-api-crds
    - name: Gateway API Documentation
      url: https://gateway-api.sigs.k8s.io/
